# Generated by Django 6.0.4 on 2026-05-01 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Client Name', max_length=200, verbose_name='name')),
                ('rfc', models.CharField(default='XAXX010101ABC', max_length=13, verbose_name='rfc')),
            ],
        ),
    ]
